server:
  port: 8084

spring:
  application:
    name: msvc-traceability

data:
  mongodb:
    uri: mongodb://localhost:27017/traceability

security:
  jwt:
    secret: unaClaveSuperSecretaYSeguraDe32Caracteres!
    expiration: 3600000

appDescription: "Microservice traceability"
appVersion: "1.0.0"
